# Client configuration to connect to the Primary cluster via NodePort.
# Used with kafka-cluster-links and kafka-mirrors CLI tools.
# These paths are local (resolved on the machine running the CLI).
bootstrap.servers=primary-control-plane:30092
security.protocol=SSL
ssl.truststore.location=certs/global.truststore.jks
ssl.truststore.password=confluent
ssl.keystore.location=certs/kafka/kafka.keystore.jks
ssl.keystore.password=confluent
ssl.key.password=confluent
