apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: primary-cluster-restclass
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  kafkaRest:
    endpoint: https://kafka.confluent.svc.cluster.local:8090
    authentication:
      type: bearer
      bearer:
        secretRef: kafka-credential
    tls:
      secretRef: rest-class-tls
