apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: secondary-link
  namespace: confluent
spec:
  sourceKafkaCluster:
    bootstrapEndpoint: secondary-control-plane:30192
    kafkaRestClassRef:
      name: secondary-remote-restclass
    tls:
      enabled: true
      secretRef: cluster-link-tls
    authentication:
      type: mtls
  destinationKafkaCluster:
    bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
    tls:
      enabled: true
    authentication:
      type: mtls
    kafkaRestClassRef:
      name: primary-cluster-restclass
  mirrorTopics:
    - name: product-pageviews
    - name: confluent.connect-offsets
  mirrorTopicOptions:
    autoCreateTopics:
      enabled: true
      topicFilters:
        - name: "product-pageviews"
          patternType: "LITERAL"
          filterType: "INCLUDE"
        - name: "confluent.connect-offsets"
          patternType: "LITERAL"
          filterType: "INCLUDE"
  configs:
    consumer.offset.sync.enable: "true"
