apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: secondary-remote-restclass
  namespace: confluent
spec:
  kafkaRest:
    endpoint: https://secondary-control-plane:30182
    authentication:
      type: bearer
      bearer:
        secretRef: clusterlink-credential
    tls:
      secretRef: rest-class-tls
    kafkaClusterID: "secondaryCluster-12345"
